### ISSUE TITLE
Your CI pipeline needs an enema

### ISSUE THREAD

**Issue by Cloud-RF** [deptofdefense/AndroidTacticalAssaultKit-CIV#14]
A PR (#4) failed step 1 (build) in your pipeline due to a lack of space left on the device.

Pipeline ID:
https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/runs/1349971846

`
Execution failed for task ':ATAKMapEngine:lib:copyCivSdkJniLibsProjectAndLocalJars'.
1624
1 exception was raised by workers:
1625
  java.nio.file.FileSystemException: /home/runner/work/AndroidTacticalAssaultKit-CIV/AndroidTacticalAssaultKit-CIV/atak/ATAKMapEngine/lib/build/intermediates/stripped_native_libs/civSdk/out/lib/armeabi-v7a/libgdal.so -> /home/runner/work/AndroidTacticalAssaultKit-CIV/AndroidTacticalAssaultKit-CIV/atak/ATAKMapEngine/lib/build/intermediates/library_and_local_jars_jni/civSdk/jni/armeabi-v7a/libgdal.so: No space left on device
`

**Comment by takdeveloper** [comment]
Please see https://github.com/actions/virtual-environments/issues/709

Our pipeline hadn't changed from previous builds when it spuriously started failing. The issue appeared to be mitigated upstream to some degree as the basic workflow executed on PR which had failed started passing again after updates for the `set-env` deprecation (https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/pull/19).

The `Release SDK` workflow now includes some cleanup during the process (https://github.com/deptofdefense/AndroidTacticalAssaultKit-CIV/commit/4429a31ea3346ee1c98e7a7ba8fc4819cb546870#diff-c45778f819ae6d949376e81fa8752fe5b1e253a848be8f6f809fdce81c025c79).

Marking this as closed since pipelines are completing successfully again; we will monitor and address as possible if space issues are observed in the future.
